-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
--
--
-- return {
--   "nvim-neotest/neotest",
--   lazy = true,
--   dependencies = {
--     "zidhuss/neotest-minitest",
--   },
--   config = function()
--     require("neotest.Config").setup({
--       adapters = {
--         require("neotest-minitest"),
--       },
--     })
--   end,
--
--   require("neotest-minitest")({
--     test_cmd = function()
--       return vim.tbl_flatten({
--         "bundle",
--         "exec",
--         "rails",
--         "test",
--       })
--     end,
--   }),
-- }
